# https://help.github.com/en/articles/metadata-syntax-for-github-actions

author: 'OskarStark'

branding:
    icon: 'check'
    color: 'blue'

description: 'Use PHPStan via GithubAction.'

name: 'OSKAR-phpstan'

inputs:
  version:
    description: phpstan version, defaults to latest
    required: false
    default: latest

runs:
    using: 'docker'
    image: 'docker://oskarstark/phpstan-ga:${{ inputs.version }}'
