name: "Build and push docker image"

on:
    push:
        branches:
            - 'master'
        paths:
            - ".github/workflows/build-docker.yaml"
            - "**"

env:
    IMAGE: "oskarstark/phpstan-ga"

jobs:
    build:
        name: 'Build and Push'
        runs-on: "ubuntu-latest"
        steps:
            - name: 'Checkout'
              uses: 'actions/checkout@v3'
              with:
                ref: '${{ github.head_ref }}'

            - name: Login to Dockerhub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v2.9.1

            - name: Build and push images
              uses: docker/build-push-action@v4
              with:
                  push: true
                  builder: ${{ steps.buildx.outputs.name }}
                  tags: |
                      ${{env.IMAGE}}:latest
                  file: Dockerfile
                  context: .
                  cache-from: type=gha
                  cache-to: type=gha,mode=max
