name: Watch

on:
    workflow_dispatch:
    schedule:
        - cron: '30 */4 * * *'

jobs:
    update-version:
        name: Automatically get latest PHPStan version and commit

        runs-on: ubuntu-latest

        outputs:
            latest: ${{ steps.fetch_version.outputs.latest }}

        steps:
            - name: "Checkout code"
              uses: actions/checkout@v2
              with:
                  ref: master

            - name: "Update Dockerfile and action.yml"
              id: fetch_version
              run: |
                  latest=$(curl -s https://packagist.org/packages/phpstan/phpstan.json|jq '[.package.versions[]|select(.version|test("^\\d+\\.\\d+\\.\\d+$"))|.version]|max_by(.|[splits("[.]")]|map(tonumber))')
                  latest=$(echo $latest | tr -d '"')
                  echo "Latest PHPStan version is $latest"
                  echo ::set-output name=latest::$latest
                  sed -i -re "s/ENV VERSION=.*/ENV VERSION=$latest/" Dockerfile
                  cat Dockerfile
                  sed -i -re "s/phpstan-ga:[0-9.]+/phpstan-ga:$latest/" action.yml
                  cat action.yml

            - name: "Commit updated files"
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_author: "Oskar Stark <oskarstark@googlemail.com>"
                  commit_message: "Enhancement: Upgrade to PHPStan ${{ steps.fetch_version.outputs.latest }}"
                  commit_user_email: "oskarstark@googlemail.com"
                  commit_user_name: "Oskar Stark"
                  branch: master

    create-release:
        needs: update-version

        name: Create a release

        runs-on: ubuntu-latest

        steps:        
            - name: "Create Release"
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ update-version.outputs.latest }}
                  release_name: "Use PHPStan ${{ update-version.outputs.latest }}"
                  draft: false
                  prerelease: false
